language: python
python:
  - "3.7"
  - "3.8"
branches:
  only:
    - main
services: airflow-provider-aliyun-rocketmq
cache: pip
before_install:
  - sudo apt-get update
  - sudo apt-get install sqlite3=3.36
install: make dev
script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
