dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  only:
    - main
services: mysql
env:
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql://root:@127.0.0.1/airflow
cache: pip
install: make dev
script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
