language: python
python:
  - "3.7"
  - "3.8"
branches:
  only:
    - main
services: airflow-provider-aliyun-rocketmq
cache: pip
install: make dev
script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
