dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
branches:
  only:
    - main
services: aliyun-rocketmq
cache: pip
before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install sqlite3
install: make dev
script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
