dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
branches:
  only:
    - main
services: airflow-provider-aliyun-rocketmq
cache: pip
before_install:
  - sudo add-apt-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -q update
  - sudo apt-get -y install sqlite3=3.15.0~travis1
  - sqlite3 --version
install: make dev
script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
